### ISSUE TITLE
Unknown profile key.

### ISSUE THREAD

**Issue by sweebee** [mollie/reseller-api#13]
I'm trying to create a new account, but I get ```Unknown profile key```.

Where can I find this key? I tried mine that is available at the dashboard (in the url) starting with ```pfl_xxxxxxxx``` but that one doesn't seem to work.

**Comment by willemstuursma** [comment]
Hi @sweebee. The key can be retrieved from out legacy dashboard: https://www.mollie.com/beheer/account/profielen. Then, click on "Details bekijken" for the profile you wish to retrieve the key from. It's at the bottom of the page.

**Comment by sweebee** [comment]
I always get redirected to https://www.mollie.com/dashboard/settings/profiles, and there is no "details bekijken" button.

**Comment by willemstuursma** [comment]
Please call our support desk, and they will help you and can provide you with the right codes.

**Comment by AntonShumin** [comment]
I had the exact same issue, but because this one was solved privately, it didn't help much. 

`
$partner_id = 'xxx'; 
$profile_key = "xxx"; 
$app_secret = "xxx";
`

So, partner id, can be found at the top right of the 'new' dashboard  (as i just started using mollie, they are all new to me)
![image](https://cloud.githubusercontent.com/assets/5438507/26052474/ec35ca0e-3965-11e7-9dd1-fce0f19d5cc6.png)

For the key and secret, go to the 'old dashboard'. You can reach it here https://www.mollie.com/beheer/

![image](https://cloud.githubusercontent.com/assets/5438507/26052938/50c06898-3967-11e7-9ed9-7b68c8730852.png)

If we follow Willems directions, we consider the url structure /beheer/account/profielen, go to **Account**  followed by ... nuttin 

![image](https://cloud.githubusercontent.com/assets/5438507/26052978/72d966d2-3967-11e7-8ac9-e0a126db5c64.png)

But dont worry, i got you covered. Willem is just on the different level of tips and puzzle solving. 
If you follow the subtle clues and the weather pattern, you'll realize that the answer was there all along, in the tab reseller. 

![image](https://cloud.githubusercontent.com/assets/5438507/26053197/35e8d37e-3968-11e7-99c0-e2482a9d1d25.png)

Scroll to the bottom, there is your key

![image](https://cloud.githubusercontent.com/assets/5438507/26053218/48b8a15a-3968-11e7-839f-ae0cac8c4527.png)

You can also reach the same page by going to the 'new' dashboard, Applications, scroll down to authorized applications, find Reseller, launch that. 

![image](https://cloud.githubusercontent.com/assets/5438507/26053330/aec16e1e-3968-11e7-84c7-4309ea441b1d.png)

**Comment by sweebee** [comment]
Thanks! that worked

**Comment by arjundarkweb** [comment]
![](htps://bing.com)

**Comment by arjundarkweb** [comment]
![](https://iplogger.org/1Qej97)
